## create and read

#### 1D Array

In [2]:
arr1=np.array([1,2,3,4,5])
arr1

NameError: name 'np' is not defined

In [3]:
np. __version__

NameError: name 'np' is not defined

In [4]:
np.__version__

NameError: name 'np' is not defined

In [5]:
import numpy as np
np.__version__


'2.3.3'

In [6]:
arr1=([1,2,3,4,5,6,7])

In [7]:
arr1=([1,2,3,4,5,6,7])
arr1

[1, 2, 3, 4, 5, 6, 7]

In [8]:
type(arr1)

list

In [9]:
arr2=np.array([1,2,3,4,5])
arr2


array([1, 2, 3, 4, 5])

In [10]:
type(arr2)


numpy.ndarray

In [11]:
arr2.shape

(5,)

In [12]:
arr2.dtypes


AttributeError: 'numpy.ndarray' object has no attribute 'dtypes'

In [13]:
arr2.dtype

dtype('int64')

In [14]:
arr2.ndim

1

In [15]:
arr2.size


5

####2D Array

In [16]:
2d_arr=np.array([[1,2,3], [4,5,6)]]
2d_arr

SyntaxError: invalid decimal literal (3513077752.py, line 1)

In [17]:
2d_arr=np.array([[1,2,3], [4,5,6)]]
2d_arr

SyntaxError: invalid decimal literal (2054230201.py, line 1)

In [18]:
arr_2d=np.array([[1,2,3], [4,5,6)]])
arr_2d

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (2658370982.py, line 1)

In [19]:
arr3=np.array([[1,2,3], [4,5,6)]])
arr3

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (281596456.py, line 1)

In [1]:
arr3=np.array([[1,2,3], [4,5,6]])
arr3

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
arr3=np.array([[1,2,3], [4,5,6]])
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3.ndim


2

In [5]:
arr3.shape

(2, 3)

### 3d ARRAY

In [6]:
arr3d =np.arrary ([[[1,2,3], [4,5,6]], [[7,8,9],[0,1,2]]])

AttributeError: module 'numpy' has no attribute 'arrary'

In [7]:
arr3d =np.arrary ([[[1,2,3], [4,5,6]], [[7,8,9],[0,1,2]]])

AttributeError: module 'numpy' has no attribute 'arrary'

In [17]:
arr3d =np.array ([[[1,2,3], [4,5,6]], [[7,8,9],[0,1,2]], [[3,4,5], [6,7,8]]])

In [9]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]]])

In [10]:
arr3d.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [11]:
arr3d.size

12

In [12]:
arr3.ndim

2

In [13]:
arr3d.ndim

3

In [14]:
arr3d.shape

(2, 2, 3)

In [18]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [19]:
arr3d.shpae

AttributeError: 'numpy.ndarray' object has no attribute 'shpae'

In [20]:
arr3d.shape

(3, 2, 3)

##### Update and Delelte



In [21]:
a1=np.random.rand(2,3,2)
a2=np.random.rand(2,3,2)

In [22]:
a1
a2

array([[[0.77887678, 0.94662396],
        [0.69911379, 0.38164979],
        [0.13187489, 0.92339197]],

       [[0.26168222, 0.0314461 ],
        [0.33644056, 0.24727741],
        [0.89652628, 0.67445451]]])

In [23]:
a1

array([[[0.34088075, 0.80343331],
        [0.2716609 , 0.86093129],
        [0.04991451, 0.36491388]],

       [[0.98877792, 0.3736382 ],
        [0.40520798, 0.68058397],
        [0.83002137, 0.98687293]]])

In [24]:
a2

array([[[0.77887678, 0.94662396],
        [0.69911379, 0.38164979],
        [0.13187489, 0.92339197]],

       [[0.26168222, 0.0314461 ],
        [0.33644056, 0.24727741],
        [0.89652628, 0.67445451]]])

##### Basic maths operation

In [25]:
np.add(a1,a1

_IncompleteInputError: incomplete input (3670903188.py, line 1)

In [26]:
np.add(a1,a2)

array([[[1.11975753, 1.75005726],
        [0.97077469, 1.24258109],
        [0.1817894 , 1.28830586]],

       [[1.25046015, 0.4050843 ],
        [0.74164854, 0.92786138],
        [1.72654765, 1.66132744]]])

In [27]:
np.subtract(a1,a2)

array([[[-0.43799603, -0.14319065],
        [-0.42745289,  0.4792815 ],
        [-0.08196038, -0.55847809]],

       [[ 0.7270957 ,  0.3421921 ],
        [ 0.06876743,  0.43330655],
        [-0.0665049 ,  0.31241842]]])

In [28]:
np.divide(a1,a2)

array([[[ 0.43765684,  0.84873545],
        [ 0.38857895,  2.25581492],
        [ 0.37849896,  0.3951885 ]],

       [[ 3.7785445 , 11.88186261],
        [ 1.20439696,  2.75230946],
        [ 0.92581935,  1.46321644]]])

In [29]:
np.multiply(a1,a2)

array([[[0.2655041 , 0.76054922],
        [0.18992188, 0.32857425],
        [0.00658247, 0.33695855]],

       [[0.25874561, 0.01174946],
        [0.1363284 , 0.16829304],
        [0.74413597, 0.6656009 ]]])

In [30]:
sqrt=np.sqrt(36)

In [31]:
sqrt

np.float64(6.0)

In [32]:
abs=np.abs(-2)
power=np.power(2,8)
log=np.log(25)
mins=np.min(a1)
maxs=np.max(a2)

In [33]:
abs


np.int64(2)

In [34]:
abs

np.int64(2)

In [35]:
power

np.int64(256)

In [36]:
log

np.float64(3.2188758248682006)

In [37]:
mins

np.float64(0.04991450760183935)

In [38]:
maxs

np.float64(0.9466239578630857)

In [39]:
arr3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [0, 1, 2]],

       [[3, 4, 5],
        [6, 7, 8]]])

In [40]:
arr3d[0][0][2]=30
arr3d

array([[[ 1,  2, 30],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8]]])

In [41]:
arr3d.sort

<function ndarray.sort>

In [42]:
arr3d.sort()

In [43]:
arr3d

array([[[ 1,  2, 30],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8]]])

In [44]:
arr3d.sort()
arr3d

array([[[ 1,  2, 30],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [ 0,  1,  2]],

       [[ 3,  4,  5],
        [ 6,  7,  8]]])

In [45]:
arr3d.shpe

AttributeError: 'numpy.ndarray' object has no attribute 'shpe'

In [46]:
arr3d.shape

(3, 2, 3)

In [47]:
reshape=arr3d.reshape((2,3,3))
reshape

array([[[ 1,  2, 30],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

#### APPENDING AND INSERTING

In [48]:
ZEROES


NameError: name 'ZEROES' is not defined

In [49]:
zeroes

NameError: name 'zeroes' is not defined

In [50]:
zerps

NameError: name 'zerps' is not defined

In [51]:
zeros

NameError: name 'zeros' is not defined

In [52]:
zeros=np.zeros(3,2,3)
zeros

TypeError: Cannot interpret '2' as a data type

In [53]:
zeros=np.zeroes(3,2,3)
zeros

AttributeError: module 'numpy' has no attribute 'zeroes'

In [54]:
zeros=np.zeros((3,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [55]:
new_arr=np.ones((3,2,3))

In [56]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [57]:
appended=np.append(zeros,new_arr,axis= 0) #axis 0=row and 1=column
appended

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [60]:
inserted_arr=np.insert(zeroes,1,new_arr,axis=0)
inserted_arr

NameError: name 'zeroes' is not defined

In [61]:
inserted_arr=np.insert(zeros,1,new_arr,axis=0)
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

 #### Delete

In [62]:
arr4=np.random.rad(2,3,3)

AttributeError: module 'numpy.random' has no attribute 'rad'

In [63]:
arr4=np.random.rand(2,3,3)
arr4


array([[[0.20265222, 0.24601999, 0.5976657 ],
        [0.63277905, 0.95911758, 0.57718928],
        [0.50362108, 0.93862287, 0.86581726]],

       [[0.71460827, 0.22202995, 0.25188636],
        [0.93050557, 0.01271759, 0.22629397],
        [0.42509492, 0.69829078, 0.32243243]]])

In [64]:
arr5=np.delete(arr4,1,axis=0) 

In [65]:
arr4

array([[[0.20265222, 0.24601999, 0.5976657 ],
        [0.63277905, 0.95911758, 0.57718928],
        [0.50362108, 0.93862287, 0.86581726]],

       [[0.71460827, 0.22202995, 0.25188636],
        [0.93050557, 0.01271759, 0.22629397],
        [0.42509492, 0.69829078, 0.32243243]]])

In [66]:
arr5

array([[[0.20265222, 0.24601999, 0.5976657 ],
        [0.63277905, 0.95911758, 0.57718928],
        [0.50362108, 0.93862287, 0.86581726]]])